sudo: required
services:
  - docker

before_install: 
  - docker build -t pita/docker-react -f Dockerfile.dev .

script:  
  - docker run -e CI=true pita/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-161619979539"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure:"$AWS_SECRET_KEY"



# http://dockerreact-env.eba-gerrs4t8.us-east-1.elasticbeanstalk.com/
